server: 
  port: 3344 
  
spring:
  application:
    name: comprehensivefirstaid-config-server-3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/snailVei/service-config.git #GitHub上面的git仓库名字
#          uri: https://github.com/snailVei/comprehensivefirstaid.git


